# Simulation mode: mono (monolithic) or disagg (prefill/decode disaggregated)
mode: disagg

# Horizon and warmup
sim_seconds: 600.0
warmup_seconds: 60.0
random_seed: 42

arrival:
  rate_per_s: 2.0

prompt_tokens:
  mean: 6.0
  sigma: 0.9
  min_value: 8

output_tokens:
  mean: 6.0
  sigma: 1.1
  min_value: 16

cluster_mono:
  num_gpus: 4
  prefill_tokens_per_s: 8000.0
  decode_tokens_per_s: 2000.0

cluster_disagg:
  prefill_gpus: 2
  decode_gpus: 2
  prefill_tokens_per_s: 8000.0
  decode_tokens_per_s: 2000.0